deafault: &default
	adapter: mongoose

  # Mongoose options <http://mongoosejs.com/docs/connections.html>
  options:
    db:
      native_parser: true
    server:
      poolSize: 5

production:
  <<: *default
  uri: {{ process.env.MONGODB_URI }}

development:
  <<: *default
  uri: mongodb://localhost/sample

test:
  <<: *default
  uri: mongodb://localhost/sample