deafault: &default
  adapter: mongoose
  options:
    db:
      native_parser: true
    server:
      poolSize: 5

production:
  <<: *default
  uri: {{ process.env.MONGODB_URI }}
  name: sample

development:
  <<: *default
  uri: mongodb://localhost/
  name: sample_dev

test:
  <<: *default
  uri: mongodb://localhost/
  name: sample_test
